version: "3"
services: 
    elastalert:
        image: linuxcloudops/elastalert:7.5.0
        ports: 
        - "3030:3030"
        volumes: 
        - ./config/elastalert.yaml:/opt/elastalert/config.yaml
        - ./config/config.json:/opt/elastalert-server/config/config.json
        - ./rules:/opt/elastalert/rules
        container_name: elastalert