FROM docker.elastic.co/kibana/kibana:7.5.0

RUN /usr/share/kibana/bin/kibana-plugin install  https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.1.0/elastalert-kibana-plugin-1.1.0-7.5.0.zip